stages:
  - build-docker-image
  - deploy

push_docker_image_to_gcr:
  stage: deploy
  needs: ["build-docker-image"]

  script:
      - curl --header "PRIVATE-TOKEN: ${CI_JOB_TOKEN}" "https://gitlab.be-md.ncbi.nlm.nih.gov/api/v4/projects/3171/repository/files/crane0.9.0.tar.gz/raw?ref=singleton"
      - tar -xvzf crane0.9.0.tar.gz && chmod +x crane
      - export CLOUDSDK_CONFIG=$CI_PROJECT_DIR
      - export GCP_ARTIFACT_REGISTRY_URL=$(echo ${GCP_ARTIFACT_REGISTRY} | cut -d"/" -f1)

    # login to GitLab Registry
      - crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

    # login to Google Artifact Registry
      - gcloud auth activate-service-account --key-file=${GCP_IMAGE_PUSH_CREDENTIALS}
      - gcloud auth print-access-token | crane auth login -u oauth2accesstoken --password-stdin ${GCP_ARTIFACT_REGISTRY_URL}

    # copy image
      - crane copy "${CI_REGISTRY_IMAGE}/${CI_COMMIT_REF_}${SLUG_OR_NAME}-${SERV_NAME}:${CI_COMMIT_SHA}" "${GCP_ARTIFACT_REGISTRY}/${CI_COMMIT_REF_}${SLUG_OR_NAME}-${SERV_NAME}:${CI_COMMIT_SHA}"
      - crane tag "${GCP_ARTIFACT_REGISTRY}/${CI_COMMIT_REF_}${SLUG_OR_NAME}-${SERV_NAME}:${CI_COMMIT_SHA}" "latest"

build-docker-image:
  stage: build-docker-image
  image: gitlabreg.be-md.ncbi.nlm.nih.gov:5050/pd/do/ci/public-docker-images/kaniko-executor:v1.6.0-debug
  script:
    - mkdir -p /kaniko/.docker
    - echo "{\"auths\":{\"${CI_REGISTRY}\":{\"auth\":\"$(printf "%s:%s" "${CI_REGISTRY_USER}" "${CI_REGISTRY_PASSWORD}" | base64 | tr -d '\n')\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context "./" --dockerfile "Dockerfile" --destination "${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}-${IMAGE_NAME}:${CI_COMMIT_SHA}" --destination "${CI_REGISTRY_IMAGE}/${CI_COMMIT_BRANCH}-${SERVICE_NAME}:latest" --single-snapshot --push-retry 2

